#!/bin/bash
#+
# This script updates all Git repositories it finds in subdirectories
# of the current directory. It only rebases the currently-checked-out
# local branch to the same-named remote one from the remote named “origin”.
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-
for d in $(find . -type d -name .git -print); do
    d="${d%/.git}"
    d="${d#./}"
    echo "$d"
    BRANCH=$(cd -- "$d" && git branch | perl -nle '/^\* (\S+)$/ && print "$1"')
    (cd -- "$d" && git fetch && git rebase origin/$BRANCH $BRANCH)
done

